# Generated by Django 5.1.5 on 2025-04-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="encrypted_password",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
