# Generated by Django 5.1.5 on 2025-09-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
        ("customer", "0004_rename_location_userprofile_address_businessprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="businessprofile",
            name="dealing_with",
        ),
        migrations.AddField(
            model_name="businessprofile",
            name="dealing_with",
            field=models.ManyToManyField(to="catalog.category"),
        ),
    ]
